remote_theme: just-the-docs/just-the-docs
#theme: just-the-docs
color_scheme: sbb

title: API Principles
description: The SBB API Principles
baseurl: "/api-principles"
url: "https://schweizerischebundesbahnen.github.io"
favicon_ico: "/assets/favicon.ico"

permalink: pretty
search_enabled: true
heading_anchors: true
aux_links:
    "API Principles on GitHub":
      - "//github.com/schweizerischebundesbahnen/api-principles"
